/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

/**
 *
 * @author Pedr0xh
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUsuarioCadastro = new javax.swing.JMenuItem();
        menuCadastroItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegistrarEmprestimo = new javax.swing.JMenuItem();
        menuDevolucao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuHistorico = new javax.swing.JMenuItem();
        menuMaisEmprestados = new javax.swing.JMenuItem();
        menuAtrasados = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setText("Sistema De Gerenciamento De Empréstimos");

        jMenu1.setText("Cadastros");

        menuUsuarioCadastro.setText("Cadastrar Usuario");
        menuUsuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarioCadastro);

        menuCadastroItem.setText("Cadastrar Item");
        menuCadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Emprestimos/Devoluções");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuRegistrarEmprestimo.setText("Emprestimo");
        menuRegistrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarEmprestimoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistrarEmprestimo);

        menuDevolucao.setText("Devolução");
        menuDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDevolucaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuDevolucao);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatorios");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuHistorico.setText("Historico");
        menuHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistoricoActionPerformed(evt);
            }
        });
        jMenu3.add(menuHistorico);

        menuMaisEmprestados.setText("Mais Emprestados");
        menuMaisEmprestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaisEmprestadosActionPerformed(evt);
            }
        });
        jMenu3.add(menuMaisEmprestados);

        menuAtrasados.setText("Atrasados");
        menuAtrasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAtrasadosActionPerformed(evt);
            }
        });
        jMenu3.add(menuAtrasados);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMaisEmprestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaisEmprestadosActionPerformed
        RelatorioMaisEmprestados mais = new RelatorioMaisEmprestados();
        mais.setVisible(true);
    }//GEN-LAST:event_menuMaisEmprestadosActionPerformed

    private void menuUsuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioCadastroActionPerformed
        CadastroUsuario userRegister = new CadastroUsuario();
        userRegister.setVisible(true);
    }//GEN-LAST:event_menuUsuarioCadastroActionPerformed

    private void menuCadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroItemActionPerformed
        CadastrarItem itemRegister = new CadastrarItem();
        itemRegister.setVisible(true);
    }//GEN-LAST:event_menuCadastroItemActionPerformed

    private void menuRegistrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarEmprestimoActionPerformed
        RegistraEmprestimo emprestimoRegister = new RegistraEmprestimo();
        emprestimoRegister.setVisible(true);
    }//GEN-LAST:event_menuRegistrarEmprestimoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        DevolveEmprestimo devolucao = new DevolveEmprestimo();
        devolucao.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDevolucaoActionPerformed
        DevolveEmprestimo devolucao = new DevolveEmprestimo();
        devolucao.setVisible(true);
    }//GEN-LAST:event_menuDevolucaoActionPerformed

    private void menuHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistoricoActionPerformed
        ConsultaHistorico historico = new ConsultaHistorico();
        historico.setVisible(true);
    }//GEN-LAST:event_menuHistoricoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void menuAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAtrasadosActionPerformed
         RelatorioEmprestimosAtrasados  relatorioAtrasado = new RelatorioEmprestimosAtrasados();
        relatorioAtrasado.setVisible(true);
    }//GEN-LAST:event_menuAtrasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JMenuItem menuAtrasados;
    private javax.swing.JMenuItem menuCadastroItem;
    private javax.swing.JMenuItem menuDevolucao;
    private javax.swing.JMenuItem menuHistorico;
    private javax.swing.JMenuItem menuMaisEmprestados;
    private javax.swing.JMenuItem menuRegistrarEmprestimo;
    private javax.swing.JMenuItem menuUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
