/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import dao.EmprestimoDAO;
import dao.ItemDAO;
import dao.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Emprestimo;
import model.Item;
import model.Usuario;

/**
 *
 * @author Gabriel
 */
public class RegistraEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form RegistraEmprestimo
     */
    public RegistraEmprestimo() {
        initComponents();
        preencherComboUsuarios();
        preencherComboItens();
    }
    
    public void preencherComboUsuarios(){
        UsuarioDAO cDAO = new UsuarioDAO();
        List<Usuario> ListaUsuarios = cDAO.getTodosUsuarios();
        for(Usuario u : ListaUsuarios){
           comboBoxUsuario.addItem(u.getNome());
        }
    }
    
    public void preencherComboItens(){
        ItemDAO iDAO = new ItemDAO();
        List<Item> ListaItens = iDAO.getDisponiveis();
        comboBoxItem.removeAllItems(); // Limpa a comboBox para evitar duplicação
        for(Item i : ListaItens){
           comboBoxItem.addItem(i.getNome());
        }
    }
    
     public void atualizar(){
        preencherComboItens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxUsuario = new javax.swing.JComboBox();
        comboBoxItem = new javax.swing.JComboBox();
        btnRegistraEmprestimo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Registrar Emprestimo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Item:");

        btnRegistraEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistraEmprestimo.setText("Registrar Emprestimo");
        btnRegistraEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistraEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistraEmprestimo)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxUsuario, 0, 264, Short.MAX_VALUE)
                            .addComponent(comboBoxItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxUsuario))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnRegistraEmprestimo)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistraEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistraEmprestimoActionPerformed
        Emprestimo e = new Emprestimo();
        String nomeUser  = ((String)comboBoxUsuario.getSelectedItem());
        String nomeItem = ((String)comboBoxItem.getSelectedItem());
  
        EmprestimoDAO pd = new EmprestimoDAO();
        UsuarioDAO uDAO = new UsuarioDAO();
        Usuario u = new Usuario();
        ItemDAO iDAO = new ItemDAO();
        Item i = new Item();
        
        u = uDAO.buscarUsuarioPorNome(nomeUser);
        i = iDAO.buscarItemPorNome(nomeItem);
        e.setItem(i);
        e.setUsuario(u);
        pd.inserir(e);
        JOptionPane.showMessageDialog(rootPane, "Emprestimo cadastrado com sucesso!", "INFO", JOptionPane.INFORMATION_MESSAGE);
        
        atualizar();
    }//GEN-LAST:event_btnRegistraEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistraEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRegistraEmprestimo;
    private javax.swing.JComboBox comboBoxItem;
    private javax.swing.JComboBox comboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
